/* Generated By:JavaCC: Do not edit this line. RobotConstants.java */
package uniandes.lym.robot.control;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface RobotConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int T_MOVER = 5;
  /** RegularExpression Id. */
  int T_TURNRIGHT = 6;
  /** RegularExpression Id. */
  int T_PONER = 7;
  /** RegularExpression Id. */
  int T_RECOGER = 8;
  /** RegularExpression Id. */
  int WALK = 9;
  /** RegularExpression Id. */
  int ROT = 10;
  /** RegularExpression Id. */
  int LOOK = 11;
  /** RegularExpression Id. */
  int DROP = 12;
  /** RegularExpression Id. */
  int FREE = 13;
  /** RegularExpression Id. */
  int PICK = 14;
  /** RegularExpression Id. */
  int GRAB = 15;
  /** RegularExpression Id. */
  int WT = 16;
  /** RegularExpression Id. */
  int NOP = 17;
  /** RegularExpression Id. */
  int BLOCK = 18;
  /** RegularExpression Id. */
  int IF = 19;
  /** RegularExpression Id. */
  int DEF = 20;
  /** RegularExpression Id. */
  int BLOCKED = 21;
  /** RegularExpression Id. */
  int FACING = 22;
  /** RegularExpression Id. */
  int CAN = 23;
  /** RegularExpression Id. */
  int NOT = 24;
  /** RegularExpression Id. */
  int PI = 25;
  /** RegularExpression Id. */
  int PD = 26;
  /** RegularExpression Id. */
  int NORTH = 27;
  /** RegularExpression Id. */
  int SOUTH = 28;
  /** RegularExpression Id. */
  int EAST = 29;
  /** RegularExpression Id. */
  int WEST = 30;
  /** RegularExpression Id. */
  int IZQ = 31;
  /** RegularExpression Id. */
  int DER = 32;
  /** RegularExpression Id. */
  int BACK = 33;
  /** RegularExpression Id. */
  int T_BALLOONS = 34;
  /** RegularExpression Id. */
  int T_CHIPS = 35;
  /** RegularExpression Id. */
  int CONSTANT = 36;
  /** RegularExpression Id. */
  int DIGIT = 37;
  /** RegularExpression Id. */
  int ID = 38;
  /** RegularExpression Id. */
  int LETTER = 39;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"Move\"",
    "\"TURNRIGHT\"",
    "\"Put\"",
    "\"Pick\"",
    "\"walk\"",
    "\"rotate\"",
    "\"look\"",
    "\"drop\"",
    "\"free\"",
    "\"pick\"",
    "\"grab\"",
    "\"walkTo\"",
    "\"NOP\"",
    "\"block\"",
    "\"if\"",
    "\"define\"",
    "\"blocked?\"",
    "\"facing?\"",
    "\"can\"",
    "\"not\"",
    "\"(\"",
    "\")\"",
    "\"N\"",
    "\"S\"",
    "\"E\"",
    "\"W\"",
    "\"left\"",
    "\"right\"",
    "\"back\"",
    "\"BALLOONS\"",
    "\"CHIPS\"",
    "<CONSTANT>",
    "<DIGIT>",
    "<ID>",
    "<LETTER>",
    "\",\"",
  };

}
